apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
    - fabmedical-mix-ingress.eastus.cloudapp.azure.com/
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer